---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: logged-in-or-beta-user-on-phone

description: Phone users who are either logged in, or beta users.

conditions:
  anyOf:
    - anyOf:
        - group:
            name: targetPhoneUse
    - property:
        name: isLoggedIn
        operator: is-true
    - anyOf:
        - group:
            id: 83f5cc01-05cf-427d-561a-ed34f6655093
        - group:
            id: 3f140235-04c7-4593-78c5-4d0c61e337b3
        - group:
            id: d0e7ed70-0573-48ab-42b3-b36a59e825b2
