---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: parent

description: 

conditions:
  allOf:
    - property:
        name: rox.distinct_id
        operator: in-array
        operands:
            - "1"
            - "2"
