---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: numberSplit

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: 21

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
            - "1231232222"
    flagValue:
      valueWrittenInCode: true
